### ISSUE TITLE
另外DefaultLoadMoreView中的文字绘制时候，paint没有设置抗锯齿

### ISSUE THREAD

**Issue by threeloe** [HomHomLin/Android-PullToRefreshRecyclerView#8]
另外DefaultLoadMoreView中的文字绘制时候，paint没有设置抗锯齿

**Comment by HomHomLin** [comment]
See this change:[change](https://github.com/HomHomLin/Android-PullToRefreshRecyclerView/commit/4ba2e8b476a0e7d9139f6704f38e3f5781595735)
